include("test_setup.jl")

include("test_read_data.jl")
include("test_logistic.jl")
include("test_zja.jl")
include("test_split.jl")
include("test_large_t.jl")
include("test_profile.jl")
include("test_ais.jl")
include("test_utils.jl")
include("test_barriers.jl")
include("test_mix.jl")
include("test_sais.jl")
include("test_unid.jl")